### ISSUE TITLE
Include the two missing memoryone strategies (already written: just commented out - need tests etc...)

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#102]
@marcharper wrote a big pull request that took me a little while to merge as it needed tests etc...

I ended up commenting out two of the strategies: fa579594cf8e285a05a0cf4808d1133aaebdb771

It would be great to get them in, it just needs some tests and a PR that clarifies a couple of things.

**Comment by marcharper** [comment]
They are both zero determinant strategies. ZDChi is correct as submitted but ZDGTFT2 needs to be fixed for your game matrix. I left it in since it did reasonably well.

See the following references:
http://www.pnas.org/content/109/26/10409.abstract
http://www.pnas.org/content/109/26/10134.short
http://www.nr.com/whp/StewartPlotkinExtortion2012.pdf

as well as this blog entry:

https://golem.ph.utexas.edu/category/2012/07/zerodeterminant_strategies_in.html

**Comment by drvinceknight** [comment]
Thanks @marcharper, will get to it at some point. References are very helpful.

**Comment by drvinceknight** [comment]
Hey @marcharper I've worked on this a bit (the first strategy): https://github.com/Axelrod-Python/Axelrod/tree/102-ZDChi

Note that reading through the original paper the assumption there does not hold here as the game here aims to minimize the utilities. So the condition T>R>P>S is actually inverted. Without spending a while looking at the paper do you think that this would have an effect on the values for p_1, p_2, p_3, p_4?

I note for example that the test I have added gives a value of four_vector the one for p_4 to be greater than 1.

Let me know what you think before I open a pull request to get this in the library, it wan't actually need much work now.

The second missing strategy though I have not gotten to at all yet.

**Comment by drvinceknight** [comment]
- [File](https://github.com/Axelrod-Python/Axelrod/blob/102-ZDChi/axelrod/strategies/memoryone.py)
- [Test file (see line 200)](https://github.com/Axelrod-Python/Axelrod/blob/102-ZDChi/axelrod/tests/test_memoryone.py)

**Comment by drvinceknight** [comment]
Have checked through paper (which is a really nice paper btw - I had not actually gotten around to reading it). This PR #144 incorporates the first strategy, I will make my way to the second when I get a chance.

**Comment by marcharper** [comment]
I'm not sure that the conditions matter as long as the Press and Dyson determinant is used correctly. I can try to work out the correct values for ZDGTFT2, unfortunately that reference is a light on details.

**Comment by drvinceknight** [comment]
I had a hard time going for the ZDGTFT2 myself because of lack of
references. It would be good to have it in terms of the RPST values
though...

I'd suggest waiting: on #148 we're discussing changing the default payoffs
to be in line with the payoffs in the original paper.

**Comment by drvinceknight** [comment]
@marcharper #152 (which is a merged PR) now means that the default behaviour of the game is in line with literature. For ZDGTFT2 though, the out of the box version from that blog post still has some hard coded values, if you (or indeed we) could get the algebra right so that it handles any given RPTS that would be ideal (I know what you mean about the paper's details being a bit weak).

Let me know what you think.

**Comment by marcharper** [comment]
I can probably make this happen....

**Comment by marcharper** [comment]
So it turns out that there are infinitely many strategies satisfying the condition in the reference, so the strategy ZDGTFT2 is not uniquely defined by the information given, and that the various ZD strategies cannot be defined for arbitrary game matrices (depends on if there are certain relations satisfied by the values R, S, T, and P), so I did the best I could and made easy parameter choices. It doesn't help that one of the references uses 1/chi where the other uses chi (!). I tried to use the variables from the reference in case anyone looks at it later (otherwise the lines of code could be reduced by a few).

I think this is the best we can do short of emailing the authors.
