### ISSUE TITLE
Add specific memory two strategies

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1063]
* A generic class for memory 2 strategies (or Gambler can be used)
* ~~The specific strategy on page 21 of this [paper](http://math.uchicago.edu/~may/REU2014/REUPapers/Li,Siwei.pdf)~~
* AON_2 and Delayed AON_1 from [Memory-n strategies of direct reciprocity](http://www.pnas.org/content/114/18/4715) [See table 1, bottom of page 4].

**Comment by drvinceknight** [comment]
Tagging @Chadys as she was working on a generic memory $m$ strategy. (I think :))

**Comment by Chadys** [comment]
I was working on a generic NTitsForMTats, N, M and starting move as parameters. Planning to finally get back to it after I finish work on the 21st :)

**Comment by drvinceknight** [comment]
Ah yes! Apologies for the ping I remembered incorrectly!

**Comment by Nikoleta-v3** [comment]
I am going to work on this one! 

For implementing the two strategies (AON_2 and Delayed AON_1) the `Gambler` class could be used (as stated by @marcharper). I think it would be a good idea to have a generic `MemoryTwoPlayer` class which will just inherit from [MemoryOnePlayer](https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/memoryone.py) but will have a sixteen vector instead of four. 

 Please let know what would be preferable.

**Comment by drvinceknight** [comment]
> I think it would be a good idea to have a generic MemoryTwoPlayer class which will be similar to MemoryOnePlayer but will have a sixteen vector instead of four.

I like this idea (similar to the generic `ReactivePlayer` strategy).

**Comment by marcharper** [comment]
Either way is fine with me.
