### ISSUE TITLE
Possible Parallel Processing Strategies for Moran Process?

### ISSUE THREAD

**Issue by samuelcwl** [Axelrod-Python/Axelrod#1168]
I was looking into the `moran.py` and was wondering if there was a simple way to utilize parallel processing to speed up `mp.play()`? 

Or, perhaps, is there anyway to translate results from `tournament.play()` into a Moran process?

Thanks.

**Comment by marcharper** [comment]
Not a simple way that I'm aware of. There's the "approximate Moran process" class that uses sampling to avoid replaying matches over and over and we also utilize caching in the deterministic Match case. It's possible that otherwise all the matches needed for each round could be computed in parallel, but the approximation works pretty well in most cases.

If you are running into specific matches that are taking a long time you can exclude long run time strategies (one of the classifiers indicates is a strategy has a long run time). Most of the meta strategies in particular are long run time. We also have a large collection of precomputed results for an upcoming paper which might be useful if you are using the built in strategies.

**Comment by samuelcwl** [comment]
Thanks for this, @marcharper ! It was helpful. 

Yes, would love to see your precomputed results - are you planning on publishing these results on the repo? Or is there any other way that I could access them?

**Comment by drvinceknight** [comment]
@samuelcwl there's a pre print of this work up on the arxiv that you can find here: https://arxiv.org/abs/1707.06920

The data @marcharper mentioned is linked to in there too. :)
