### ISSUE TITLE
function 'compute_features' in ANN.py

### ISSUE THREAD

**Issue by wenmingMeng** [Axelrod-Python/Axelrod#1172]
Thanks for your work. line 72 in ANN.py, 'my_previous_d = 0 if player.history[-1] == D else 0', i think it should be 'my_previous_d = 1 if player.history[-1] == D else 0'.
Is it a typo or you did that on purpose?  And is the weights trained under this code?
Looking forward for ur reply, thanks.

**Comment by eric-s-s** [comment]
The same line also appears on line 58.

**Comment by wenmingMeng** [comment]
You mean you did that on purpose?

**Comment by drvinceknight** [comment]
I believe that's a mistake. In practice (correct me if I'm wrong @marcharper) this won't have affected the training as the weights would have just adjusted.

I believe the line should in fact be:

```
my_previous_d = 1 if player.history[-1] == D else 0
```

I believe a PR should include the fix to lines 72, 58 and also retrain the strategy (so that https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/data/ann_weights.csv is updated).


> You mean you did that on purpose?

No @eric-s-s is just (helpfully :+1:) pointing out that that mistake is on two lines (so when fixed it should be fixed in two spots).

**Comment by wenmingMeng** [comment]
Thanks a lot!

**Comment by marcharper** [comment]
I'm not sure -- we'd have to look back in the history to see what the original version does. If we do change it, there are three strategies that need to be retrained.

**Comment by marcharper** [comment]
Yeah no harm in retraining

**Comment by drvinceknight** [comment]
Cool, I'll pick this up.

**Comment by drvinceknight** [comment]
Currently running:

```
python axelrod-dojo/bin/ann_evolve.py --processes 10 --output ann_weights.csv
python axelrod-dojo/bin/ann_evolve.py --processes 10 --hidden 5 --output ann5_weights.csv
python axelrod-dojo/bin/ann_evolve.py --processes 10 --noise 0.05 --output annnoise5_weights.csv
```

@marcharper let me know if that's not right.

**Comment by marcharper** [comment]
Looks right to me
