### ISSUE TITLE
Can't reproduce Axelrod's results

### ISSUE THREAD

**Issue by marnixlenoble** [Axelrod-Python/Axelrod#1245]
If I create a tournament with axelrods first strategies Tit for Tat comes in 8th whereas it should be the winner as per the original outcome.

```python

players = [
    axl.TitForTat(),
    axl.TidemanAndChieruzzi(),
    axl.Nydegger(),
    axl.Grofman(),
    axl.Shubik(),
    axl.SteinAndRapoport(),
    axl.Grudger(),
    axl.Davis(),
    axl.RevisedDowning(revised=False),
    axl.Feld(),
    axl.Joss(),
    axl.Tullock(),
    axl.UnnamedStrategy(),
    axl.Random()
]

tournament = axl.Tournament(players)
results = tournament.play()
print(results.ranked_names)
print(results.summarise())
```

**Comment by drvinceknight** [comment]
Hi @marnixlenoble, there are two reasons for this:

1. You are not currently running with all the strategies from Axelrod's tournament (https://axelrod.readthedocs.io/en/stable/reference/overview_of_strategies.html#axelrod-s-first-tournament) as `Graaskamp` is missing. It has however been implemented in https://github.com/Axelrod-Python/Axelrod/pull/1244 but I've just not gotten around to do a new release (I'll aim to do that later today!).
2. Even with all the strategies implemented it is possible that they do not match the results reported. This could be due to poor descriptions of the originals (so implementations are as correct as possible) or incorrect reporting of results and/or incorrect implementations although the implementations in the library are fully tested, open and have been carefully reviewed.

**Comment by marcharper** [comment]
Also, how many iterations did you run? There's no guarantee that TFT will win every possible instance of the tournament.

**Comment by marnixlenoble** [comment]
Thank you for the speedy response. @drvinceknight
