### ISSUE TITLE
Revise `RevisedDowning` to match k59r

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1279]
It looks like they do not quite match at the moment.

This particular build: https://travis-ci.org/Axelrod-Python/axelrod-fortran/builds/626159813?utm_source=github_status&utm_medium=notification

shows that it failed to reproduce the same behaviour against `Alternator`.

**Comment by gaffney2010** [comment]
I took at look at this.  It looks like when the fortran was translated to python, PAST was changed to self.history[-1].  Because of where it's set in the fortran, it should actually be self.history[-2].

https://github.com/Axelrod-Python/TourExec/blob/master/src/strategies/K59R.f#L35
https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/revised_downing.py#L55

I'm going to run tests to make sure this is the case, and will create a PR.
