### ISSUE TITLE
Noisy Tournaments

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#166]
Lots of people have studied the effect of noise on the Prisoner's dilemma, in particular how it allows Tit-for-Tat to be overcome heads up.

@marcharper  added a variable to the Player class that randomly flips each play based on a background noise probability.

You can see the difference it makes [here](http://imgur.com/sF921cX,zV44yuB), where first image is with 5% noise and the second is zero noise as usual.

You can see the difference it has on the pairwise payoffs [here](http://imgur.com/a/bVYnd), the top plot is with 5% error and the bottom with 0%.

This work now just needs to move into the Tournament class so it can be controlled from a calling program.

**Comment by drvinceknight** [comment]
If you could add something to the documentation about this that would be really helpful... (Happy to help out with that but would be nice to put in the PR to make sure it's all done and we don't lose track...)

**Comment by langner** [comment]
Caching will need to be disabled with nosie on, I suppose.

**Comment by meatballs** [comment]
> Caching will need to be disabled with nosie on, I suppose.
Yep - that's one reason I think it needs to be handled in the Tournament class

**Comment by drvinceknight** [comment]
The cache really is only for the 'normal' tournaments, I would see this as another type of tournament?

**Comment by meatballs** [comment]
I'm thinking of a ```noise_threshold``` parameter to the Tournament ```__init__``` method with a default of zero. ```__init__``` would also use it to set a ```self._noisy``` variable.

I can then use ```if self._noisy:``` in the rest of the class to control the behaviour of the cache etc.

**Comment by drvinceknight** [comment]
Ok, cool. Could we add a command line parameter for noise? But if >0 then no cache is used (I have a feeling that I'm just getting to the same conclusion that you and @langner had reached: I apologise :)).

**Comment by meatballs** [comment]
> Ok, cool. Could we add a command line parameter for noise?

Yes, I'd want to bring ```noise_threshold``` in via the TournamentManager and run_axelrod.

> But if >0 then no cache is used 

Yes again. That's what ```self._noisy``` would do

**Comment by meatballs** [comment]
Perhaps I should just get on and write it!

**Comment by meatballs** [comment]
Branch 166 now contains code which should pass a noise parameter all the way from run_axelrod through to the players via the TournamentManager, Tournament and RoundRobin classes.

I still need to work on the test suite and documentation for this, but it's ready for anyone to take a look and find the inevitable bugs.

**Comment by marcharper** [comment]
The tournament output plot strategy_boxplot.png looks good to me. The strategies_payoff.png is a lot different but that is probably due to e.g. caching (so the one I posted on imgur likely wasn't correct). Looking at some of the pairwise values it seems correct as is now -- Fool Me Once for instance should quickly devolve into mutual defection against itself and many other opponents, and that's what the plot indicates.

I put a tiny PR on your 166 branch to change the command line argument for noise in run_axelrod from an int to a float.

**Comment by marcharper** [comment]
I've tested this quite a bit generating plots for various levels of noise and so far it looks good. I've got a few commits that turns the run_tournament function into something easily callable from other scripts that I can PR once this is merged. (I've got another script generating images for short movies where tournaments are run with increasing amounts of noise.)

**Comment by langner** [comment]
Do you see an increase in the standard deviations of the payoffs?

**Comment by marcharper** [comment]
I didn't calculate variance explicitly but it's pretty clear from [these plots](http://imgur.com/a/PnPyw) that the answer is yes. In order they are 0% noise, 0.5% noise, and 1% noise. Notice for the heads up play heatmap that for zero noise there is a large region in the top left where everyone is cooperating. Just a little noise affects that greatly.

The reason why is pretty simple. Take Grudger or Fool Me once -- they start defecting once their opponent defects once or twice. So against e.g. TFT, they are going to go ALL D at some point since in 200 rounds we would expect ~2 defections by TFT by accident. Same for ALLC -- Fool Me Once actually fares better under noise because it can start to exploit ALLC whereas before it would have cooperated forever.

I'm going to try to generate a movie file of these plots changing as the noise changes. The images are generating fine but the stitcher is complaining about some resolution nonsense.

**Comment by drvinceknight** [comment]
Not sure if helpful: http://www.jamesphoughton.com/2013/08/making-gif-animations-with-matplotlib.html

**Comment by langner** [comment]
@marcharper That is very cool! Notice that the std dev is calculated somewhere after the tournament and saved alongside the average, so it can be easily plotted. The ultimate qustion for me is: how does that influence the ecosystem variant? Does it cause one of the strategies to eventually dominate?

**Comment by marcharper** [comment]
Yes, it does affect the ecological simulation significantly, but doesn't seem to cause one strategy to completely dominate. I haven't played with the parameters yet.

**Comment by marcharper** [comment]
@drvinceknight Thanks! I may try that. In the past I've used ffmpeg or avconv to make video files but for some reason the plots are coming out with slightly different dimensions and that is making avconv unhappy. Looks like I need to pass in matplotlib kwargs to the Plot class
