### ISSUE TITLE
Eigen values of payoff matrix

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#234]
Oh wise ones.....

Given that we will be writing functions to calculate eigen values and vectors in #220, would computing them for the payoff matrix yield anything useful?

Would it, perhaps, give us a measure of one cohort versus another?

Is there something I can read somewhere?

**Comment by drvinceknight** [comment]
To my knowledge there is no interpretation of a direct eigen analysis of a payoff matrix. It does however fit in with Principal Component Analysis which is something I was thinking of using (although it does not immediately apply) for #138 (if you remember I mentioned this to a statistician here, it's a really interesting problem).

Of the top of my head I would say there's no immediate value in doing this though (or at least not as part of the library itself...), but I might be wrong...

**Comment by drvinceknight** [comment]
(One thing I do want to do at some point is look at equilibria analysis of the games, nothing exciting should come out of that but more 'because we can' - will most probably use Sage for that.)

**Comment by drvinceknight** [comment]
Just making sure @marcharper sees this as he might have more insight than me on this.

**Comment by marcharper** [comment]
I have not previously needed to find the eigenvectors of the pairwise payoff's matrix or to run PCA on it. But if it's easy to go ahead and expose the matrix now then I don't see any reason not to; I could see wanting the matrix for other purposes (e.g. various plots).

I was going to bring something similar previously -- when I was making images for the noisy tournaments to stitch together for a movie, there did not seem to be an easy way to pass in matplotlib parameters. I needed this because the image resolutions were coming out slightly different (and ffmpeg did not like that at all). So in general I favor having things easier to get to and configure (balanced against passing around a ton of rarely used parameters, of course).

**Comment by drvinceknight** [comment]
> But if it's easy to go ahead and expose the matrix now then I don't see any reason not to; I could see wanting the matrix for other purposes (e.g. various plots).

Do we not already have easy access to the payoff matrix? I've completely missed that: we should certainly have that :+1:

**Comment by drvinceknight** [comment]
Oh yeah sorry, we do: http://axelrod.readthedocs.org/en/latest/usage.html#payoff-matrix

```
import axelrod
strategies = [s() for s in axelrod.basic_strategies]
tournament = axelrod.Tournament(strategies)
results = tournament.play()
results.payoff_matrix
```

**Comment by marcharper** [comment]
Oh, nice. I will compute the eigen* of the payoff matrix (it will be a good test in any case) and report back if I find anything interesting.

**Comment by drvinceknight** [comment]
This (Sagemathcloud) might be a quick way to play with these things and check values etc: https://cloud.sagemath.com/projects/3b2249d5-a951-4f25-979a-571f71ccdde6/files/eigen_games.sagews

I also threw the matrix in to an actual game in case anyone wanted to play with that.

**Comment by drvinceknight** [comment]
I think we can close this? (re open if not :), just doing some tidying here instead of facing my emails...)
