### ISSUE TITLE
Remaining original strategies

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#302]
@marcharper has found fortran (?) code for some of the missing original strategies, 'translating' these to the library is worth doing.

**Comment by marcharper** [comment]
*[Axelrod's original code](http://www-personal.umich.edu/~axe/research/Software/CC/CC2.html)
*There is a library called [PRISON](http://www.lifl.fr/IPD/ipd.frame.html) that has implemented some of the original strategies (and some others).
* [CoopSim](https://github.com/jecki/CoopSim) is another good resource, and in Python

**Comment by marcharper** [comment]
Some more strategies: http://arxiv.org/pdf/cs/0609017.pdf

**Comment by marcharper** [comment]
Here are my notes on what's going on the in Axelrod FORTRAN, should anyone else try to translate a strategy:

JA = 0          ! Row Player's previous move, reported to column (player)
JB = 0          ! Col Player's previous move, reported to row (opponent)
Plays: C, D = 0, 1

Strategy Function call:
KRowFunction(JB,Move, RowGameSc,ColGameSc,RandomNumber,Row,JA) 

JB: opponent's previous play
Move: Round number
RowGameSc: player's score (cumulative)
ColGameSc: opponent's score (cumulative)
RandomNumber
Row: player ID
JA: player's previous play

This call maps to e.g.:
```
       FUNCTION K49R(J,M,K,L,R, JA)
C BY ROB CAVE
C TYPED BY JM
    k49r=ja    ! Added 7/27/93 to report own old value
      IF (M .EQ. 1) JDSUM = 0
C JDSUM IS THE TOTAL NUMBER OF DEFECTIONS SO FAR
      IF (J .EQ. 1) JDSUM = JDSUM + 1
      JDPC = (100 * JDSUM) / M
C JDPC IS THE PERCENTAGE OF DEFECTIONS SO FAR
      IF (J .EQ. 0) K49R = 0
      IF ((J .EQ. 1) .AND. (JDSUM .LE. 17)) K49R = INT(R + .5)
      IF ((J .EQ. 1) .AND. (JDSUM .GT. 17)) K49R = 1
C IF OPONENT IS OVERLU DEFECTIVE OR APPEARS
C TO BE RANDOM, THEN GIVE UP
      IF ((M .GT. 19) .AND. (JDPC .GT. 79)) K49R = 1
      IF ((M .GT. 29) .AND. (JDPC .GT. 65)) K49R = 1
      IF ((M .GT. 39) .AND. (JDPC .GT. 39)) K49R = 1
      RETURN
      END
```
That strategy at least has some comments (most do not). Some of the functions change the signature (the argument names).

In Fortran you assign the function a value, e.g. `K49R = 1`. That is returned when you later call RETURN. So the strategies are somewhat like state-machines, and you need to follow the logic to find out what is actually being returned.

You also need to know about:
[Computed GOTO](https://en.wikipedia.org/wiki/Goto#Computed_GOTO_and_Assigned_GOTO), E.g.
```
GO TO (12,24,36), INDEX
```
Goes to line 12 if index is 1, line 24 if index is 24, etc.

And also: [Archaic IF-Then-Else Forms](https://en.wikibooks.org/wiki/Fortran/Fortran_control):
```
  IF (''logicalExpression'') GO TO ''lineNumber''
  IF (''arithmeticExpression'') ''firstLineNumber'', ''secondLineNumber'', ''thirdLineNumber''
```
The second line goes to the `firstLineNumber` if the expression is less than zero, the second if equal to zero, and the third otherwise.
