### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#476]
Running the unit tests gives the following:

```
axelrod/tests/unit/test_player.py:169: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

axelrod/strategy_transformers.py:79: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

**Comment by meatballs** [comment]
Looks like Django dealt with exactly the same issue here: https://github.com/django/django/pull/4846

**Comment by meatballs** [comment]
And Scipy did so here: https://github.com/ev-br/scipy/commit/a9843db1faa1aafb05c26001b0b6d21e03149e7f

**Comment by marcharper** [comment]
Resolved with #478

**Comment by marcharper** [comment]
This is a bit of a mess -- I'd suggest reading [this thread](https://bugs.python.org/issue20438) on the Python issue tracker, and maybe [this one](https://bugs.python.org/issue25486).

The story is that the Python maintainers decided to deprecate this two years ago in Python 3.0 but not include a deprecation warning until 3.5. Plus it seems that `inspect.signature` isn't a full replacement (but for our purposes I think it's good enough). However the function isn't being removed now (since people maintaining libraries compatible with 2.7 and 3+ are upset), and it's not clear if and when the deprecated functions will be removed.

We can either adopt the scipy fix or just do nothing while the Python maintainers make up their minds. If we adopt the fix now, I vote we simply import the function from scipy (but scipy isn't currently a requirement for axelrod).

**Comment by drvinceknight** [comment]
I don't like the idea of making scipy a requirement just for this. I'd vote for doing nothing for now...

**Comment by meatballs** [comment]
Yep, let's sit tight. Too much of a mess to be worth getting into!

**Comment by drvinceknight** [comment]
I suggest we keep this issue open (just in case someone else wanted to raise it).

**Comment by marcharper** [comment]
Looks like the function won't be removed until 2.7 end-of-life (2020). Hopefully by then there's a standard solution, and if not, we can adopt scipy's approach.

**Comment by meatballs** [comment]
Should be fixable >= 02-Dec-2016 #605
