### ISSUE TITLE
Consider using a git hook to prepend the issue number to a commit message

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#647]
So that:

* Commits relating to an issue appear in on that issue's page
* Anyone using a gui git client has clickable links to the issue in their git log

This can be achieved manually but a hook removes the effort.

**Comment by drvinceknight** [comment]
Not too sure I'm excited about this one (as a blanket requirement).

Perhaps if it was appended (with a '\n') so that it appeared at the bottom
of the body of the commit message as opposed to the subject? That way it
doesn't change anything terms of the subject itself but would still have
those two advantages (obviously depending on how the gui client displays
commit messages I guess).

**Comment by meatballs** [comment]
Ah - I didn't mean as a blanket requirement!

Some people find this useful, others don't. I thought it might be nice to make it easy for those that do.

**Comment by meatballs** [comment]
and yes, the format can be whatever we want

**Comment by drvinceknight** [comment]
> Some people find this useful, others don't. I thought it might be nice to make it easy for those that do.

Absolutely.
