### ISSUE TITLE
Classification of Strategies

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#689]
In the api, I'd like to have an endpoint for the various classes of strategy (e.g. 'cheating_strategies', 'ordinary_strategies') so that we'd have urls like:

```
http://<host name>/strategy_classes
http://<host name>/strategy_classes/cheating_strategies
```
Each class would then have its membership list of strategies

I'd also like to add a class filter to the strategies endpoint, so that we's have urls like:

```
http://<host name>/strategies?cheating=True&long_run_time=False
```
which would list the strategies meeting those criteria.

To do this I have some new requirements:

1. I need to enumerate the classes which exist
2. I need an efficient method to lookup which classes a Player class belongs to

I suggest:

- We create a new ```strategy_classes``` dictionary in ```strategies.__init__.py``` mapping class name to a membership list (i.e. we move the existing lists into a new dict).
- So as not to break existing code which expects to find those lists at the module level, we loop over the dictionary and create a module attribute for each entry
- We create a new ```class_membership``` dictionary in ```strategies.__init__.py``` which maps player class name to a dictionary of booleans for each strategy class. e.g.:

```
class_membership = {
    TitForTat: {
        long_run_time: False,
        demo: True
        etc.....
    },
etc.....
}
```
The ```class_membership``` dictionary would be created by looping over the ```strategy_classes``` dictionary, so there is no extra step for adding new strategies.

**Comment by drvinceknight** [comment]
> I need to enumerate the classes which exist

I think that technically there are only two classes: `axelrod.strategies` and `axelrod.cheating_strategies`. 

> I need an efficient method to lookup which classes a Player class belongs to

I think this would correspond to the [`obey_axelrod`](http://axelrod.readthedocs.io/en/latest/tutorials/advanced/classification_of_strategies.html) function which is what is used to define if a strategy is or isn't in the `cheating_strategies` list.

I'm not a fan of `strategy_classes` corresponding to the lists the strategies are in as that's the point of the classifier dictionary which makes the number of potential classes way larger than the lists that are there. In my opinion those lists are just quick pointers

My final point is that if this were to go in: whether or not this should be in the library or just specific to the api? The player IDs add loads of value to users of the library but I don't see a use case for this as the [strategy classifier](http://axelrod.readthedocs.io/en/latest/tutorials/advanced/classification_of_strategies.html) already gives a user the ability to classify strategies (which is why we brought them in).

**Comment by drvinceknight** [comment]
(On a slightly separate/related note, it could be worth adding `long_run_time` to the player classifier dictionary...)

**Comment by meatballs** [comment]
Good point. I should just use the classifier dict!

**Comment by drvinceknight** [comment]
Cool, have opened #690. I guess long run time could be particularly relevant to the api :)
