### ISSUE TITLE
Autogenerate docs from annotations

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#812]
Use [this library](https://pypi.python.org/pypi/sphinx-autodoc-annotation/1.0) to autogenerate docs from type annotations. [@meatballs suggestion on #457]

See also #808 and #347.

**Comment by drvinceknight** [comment]
My question on #457 remains, what would this be for, the only documentation that we autogenerate is for the strategies, is this for that?

**Comment by marcharper** [comment]
Would apply to any function but right now we only really do this for strategies.

**Comment by drvinceknight** [comment]
> Would apply to any function but right now we only really do this for strategies.

I'm not sure it's needed is it?

**Comment by marcharper** [comment]
The point is that the type annotations take the place of some of what we're manually putting in docstrings now.

**Comment by drvinceknight** [comment]
I understand the point of type annotations just not sure what docs would be
autogenerated using them. We don't have much of an API documentation (which
is not a bad thing), only the strategies which we only really want the
class docstrings for (to have the list that can be searchable).

It feels like we'd add this because we can not necessarily because we need
it (from a docs point of view) but I'm perhaps missing something :)

**Comment by marcharper** [comment]
Let's revisit once we've typed more things.

**Comment by drvinceknight** [comment]
Good call. :+1:

**Comment by drvinceknight** [comment]
#822 might be relevant (hopefully we fix that before this makes a move).

**Comment by drvinceknight** [comment]
I would like to close this issue. I don't feel that automated api/reference docs are needed (or necessarily a good thing) and the tutorial format we're using doesn't need any more information.

I realise we "could", I guess I'm saying I don't think we "need" to.

**Comment by marcharper** [comment]
Ok, close it. We can always reopen it later.
